### ISSUE TITLE
Falcon cloud gov region reference and input validation incorrect

### ISSUE THREAD

**Issue by tarksum** [CrowdStrike/falcon-boshrelease#12]
https://github.com/CrowdStrike/falcon-boshrelease/blob/5046a38b5f30ee865e9b066e4958216c1a691d10/tile.yml#L112
https://github.com/CrowdStrike/falcon-boshrelease/blob/5046a38b5f30ee865e9b066e4958216c1a691d10/tile.yml#L115

Listed as gov1 should be us-gov-1

**Comment by tarksum** [comment]
With all other configuration valid and using gov1 for cloud region, when /var/vcap/packages/falcon-linux-sensor/falcon-installer executes it gets a 403 forbidden.
After bosh ssh'ing into an instance and editing /var/vcap/jobs/falcon-linux-sensor/bin/pre-start to 
export FALCON_CLOUD="us-gov-1"

The install is successful.

**Comment by redhatrises** [comment]
Hello,

Thank you for the report. Both `gov1` and `us-gov-1` should work with the version 1.3.0 which is under VMWare review. Please reopen if necessary.
