### ISSUE TITLE
Upgrading to tile version 1.3.0 references old library falcon-sensor v1.1.0

### ISSUE THREAD

**Issue by louannO** [CrowdStrike/falcon-boshrelease#15]
Crowdstrike v1.3.0 from v1.2.0 this was successfull. After the upgrade we try to "apply changes" on all other tiles such as Prisma

```
===== 2024-09-24 22:35:43 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=XX upload-stemcell /var/tempest/stemcells/light-bosh-aws-xen-hvm-ubuntu-jammy-go_agent-1.572.tgz"; Duration: 0s; Exit Status: 0
{"type": "step_finished", "id": "upload_assets.uploading_stemcell.twistlock-7f68333a49e33aa59b62"}
{"type": "step_started", "id": "migrate_variables.migrating.twistlock-7f68333a49e33aa59b62"}
{"type": "step_finished", "id": "migrate_variables.migrating.twistlock-7f68333a49e33aa59b62"}
{"type": "step_started", "id": "bosh.deploying.twistlock-7f68333a49e33aa59b62"}
===== 2024-09-24 22:35:43 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=XX --deployment=twistlock-7f68333a49e33aa59b62 deploy --no-redact /var/tempest/workspaces/default/deployments/twistlock-7f68333a49e33aa59b62.yml"
Using environment '10.225.6.11' as client 'ops_manager'

Using deployment 'twistlock-7f68333a49e33aa59b62'

  releases:
+ - name: falcon-sensor
+   version: 1.1.0
- - name: falcon-linux-sensor
-   version: 1.1.0
  
  addons:
  - name: falcon-linux-sensor
    jobs:
    - name: falcon-linux-sensor
-     release: falcon-linux-sensor
+     release: falcon-sensor
Task 1355374
Updating deployment:
  Expected task '1355374' to succeed but state is 'error'
Exit code 1

Task 1355374 | 22:35:44 | Error: Release version 'falcon-sensor/1.1.0' doesn't exist

Task 1355374 Started  Tue Sep 24 22:35:44 UTC 2024
Task 1355374 Finished Tue Sep 24 22:35:44 UTC 2024
Task 1355374 Duration 00:00:00
Task 1355374 error


===== 2024-09-24 22:35:44 UTC Finished "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=10.225.6.11 --deployment=twistlock-7f68333a49e33aa59b62 deploy --no-redact /var/tempest/workspaces/default/deployments/twistlock-7f68333a49e33aa59b62.yml"; Duration: 1s; Exit Status: 1
{"type": "step_finished", "id": "bosh.deploying.twistlock-7f68333a49e33aa59b62"}
Exited with 1.
```

checking into releases we have 
```
"falcon-linux-sensor-1.1.0.tgz",
"falcon-linux-sensor-1.1.0.tgz",
"falcon-sensor-1.3.0.tgz"
```

Should the add-on be referencing v1.3.0 instead of v1.1.0. Would deleting and reinstalling Crowstrike tile solve the issue?

**Comment by redhatrises** [comment]
You could try deleting the older releases. See https://bosh.io/docs/cli-v2/#delete-release, or yes, you can reinstall the tile.

**Comment by redhatrises** [comment]
@louannO ran through an uninstall, and here is what you need to do.

1. Uninstall only the CrowdStrike tile. Make sure to deselect all applications including the TAS tile.
2. Delete the CrowdStrike tile from the UI
3. Upload the new v1.3.0 tile, and apply the changes, and re-deploy as normal.

This should get v1.3.0 installed and shouldn't be a problem going forward.

**Comment by louannO** [comment]
@redhatrises Thanks for your comments. Deleting and reinstalling did remove reference to old version 1.1.0. 
Does this version still references ubuntu-xenial which is EOLed is this expected?

`===== 2024-09-26 04:04:32 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty --environment=10.225.6.11 --deployment=twistlock-7f68333a49e33aa59b62 deploy --no-redact /var/tempest/workspaces/default/deployments/twistlock-7f68333a49e33aa59b62.yml"
Using environment 'XXXXX' as client 'ops_manager'

Using deployment 'twistlock-7f68333a49e33aa59b62'

 releases:
+ - name: falcon-sensor
+   version: 1.3.0
 
 addons:
+ - include:
+     stemcell:
+     - os: ubuntu-jammy
+     - os: ubuntu-bionic
+     - os: ubuntu-xenial
+     - os: ubuntu-trusty
+   jobs:
+   - name: falcon-linux-sensor`

**Comment by redhatrises** [comment]
@louannO these are placement rules for an addon, and only work if those stemcells are deployed already by a customer into their environment.
