### ISSUE TITLE
falcon-linux-sensor pre-start job failed because it can't find systemctl to restart the service

### ISSUE THREAD

**Issue by fiona8953** [CrowdStrike/falcon-boshrelease#16]
When using Crowdstrike v1.3 and other service broker tiles on Cloud Foundry, we tried to remove the old [aws broker v1.4.20](https://docs.vmware.com/en/VMware-Tanzu-Service-Broker-for-AWS/1.4/documentation/GUID-index.html) tile but delete-errand failed due to pre-start job falcon-linux-sensor. failed. We re-ran the errand manually with keep-alive then ssh on the VM and found below error message in the /var/vcap/sys/log/falcon-linux-sensor/falcon-installer.log -
_2024/10/03 05:41:09 Error restarting Falcon sensor service: Could not find systemctl: /usr/bin/systemctl_
It looks like the falcon sensor installation worked but just failed because it can't find systemctl to restart the service, however it's still installed, so when we re-ran the errand manually with the same vm this time it passed and succeeded (because falcon sensor was already installed...). 

Could you please fix this issue with Crowdstrike in case it might impact other errands? Thanks.

**Comment by redhatrises** [comment]
Hello,

Can you provide the OS and OS version that the errand was run on? Also, can you provide the PATH to systemctl on the VM?

**Comment by fiona8953** [comment]
Hi @redhatrises ,

The stemcell is light-bosh-aws-xen-hvm-ubuntu-xenial-go_agent-621.969.tgz, OS: ubuntu-xenial, Version: 621.969.
PATH to systemctl on the VM is /usr/bin/systemctl.

**Comment by redhatrises** [comment]
Thanks for providing that info. This is fixed in the installer and will be fixed in the next release. Closing.
